export type DrillCategory = 'shooting' | 'ball-handling' | 'athleticism' | 'defense' | 'finishing';
export type DrillDifficulty = 'beginner' | 'intermediate' | 'advanced';

export interface Drill {
  id: string;
  title: string;
  subtitle: string;
  youtubeId: string;
  category: DrillCategory;
  difficulty: DrillDifficulty;
  durationMinutes: number;
  sets: number;
  reps: string;
  equipment: string[];
  coachNote: string;
  tags: string[];
}

export const DRILLS: Drill[] = [
  {
    id: 'drill-001',
    title: 'Steph Curry Shooting Mechanics',
    subtitle: 'NBA-level form breakdown',
    youtubeId: 'G_GkQRmOfZo',
    category: 'shooting',
    difficulty: 'intermediate',
    durationMinutes: 15,
    sets: 4,
    reps: '10 makes',
    equipment: ['basketball', 'hoop'],
    coachNote: 'Focus on your hip load and wrist snap — catch and shoot in one fluid motion.',
    tags: ['shooting', 'form', 'steph-curry'],
  },
  {
    id: 'drill-002',
    title: 'Drew Hanlen Ball-Handling Fundamentals',
    subtitle: 'Elite handle foundation',
    youtubeId: '2uDihY7Hang',
    category: 'ball-handling',
    difficulty: 'beginner',
    durationMinutes: 20,
    sets: 3,
    reps: '60 seconds each',
    equipment: ['basketball'],
    coachNote: 'Keep your eyes up the entire time. The ball should feel like an extension of your hand.',
    tags: ['ball-handling', 'drew-hanlen', 'fundamentals'],
  },
  {
    id: 'drill-003',
    title: 'PGC Basketball Athletic Training',
    subtitle: 'Explosiveness & court speed',
    youtubeId: 'eYvo-afyy98',
    category: 'athleticism',
    difficulty: 'intermediate',
    durationMinutes: 25,
    sets: 5,
    reps: '8 reps',
    equipment: ['cones', 'resistance band'],
    coachNote: 'Maximum effort on each rep. Rest 90 seconds between sets.',
    tags: ['athleticism', 'speed', 'pgc'],
  },
  {
    id: 'drill-004',
    title: 'Melo Ball-Handling Series',
    subtitle: 'Advanced crossover combos',
    youtubeId: 'OoNsv8U7hQM',
    category: 'ball-handling',
    difficulty: 'advanced',
    durationMinutes: 18,
    sets: 3,
    reps: '45 seconds each',
    equipment: ['basketball', '2 basketballs'],
    coachNote: 'Start slow, build rhythm before increasing speed.',
    tags: ['ball-handling', 'advanced', 'crossover'],
  },
  {
    id: 'drill-005',
    title: 'Catch & Shoot Off Screen',
    subtitle: 'Off-ball shooting movement',
    youtubeId: 'sD5_HBzm5aA',
    category: 'shooting',
    difficulty: 'intermediate',
    durationMinutes: 20,
    sets: 4,
    reps: '8 makes',
    equipment: ['basketball', 'hoop', 'screen partner'],
    coachNote: 'Stay low off the screen, rise to meet the pass.',
    tags: ['shooting', 'movement', 'off-screen'],
  },
  {
    id: 'drill-006',
    title: 'Lateral Defensive Slides',
    subtitle: 'Lockdown defensive footwork',
    youtubeId: 'K5pBV_QFOS4',
    category: 'defense',
    difficulty: 'beginner',
    durationMinutes: 12,
    sets: 4,
    reps: '30 seconds',
    equipment: ['cones'],
    coachNote: 'Stay in defensive stance — never cross your feet.',
    tags: ['defense', 'footwork', 'lateral'],
  },
  {
    id: 'drill-007',
    title: 'Euro Step Finishing',
    subtitle: 'Deceptive layup footwork',
    youtubeId: 'WTn9bTVY9hc',
    category: 'finishing',
    difficulty: 'intermediate',
    durationMinutes: 15,
    sets: 3,
    reps: '10 makes each side',
    equipment: ['basketball', 'hoop'],
    coachNote: 'Lead with your shoulder, protect the ball with your outside hand.',
    tags: ['finishing', 'layup', 'euro-step'],
  },
  {
    id: 'drill-008',
    title: 'Plyometric Jump Training',
    subtitle: 'Explosive vertical development',
    youtubeId: 'Qs_GcfZfOKA',
    category: 'athleticism',
    difficulty: 'advanced',
    durationMinutes: 30,
    sets: 5,
    reps: '6 reps',
    equipment: ['plyo box', 'resistance band'],
    coachNote: 'Land softly to protect your joints. Quality over quantity.',
    tags: ['athleticism', 'vertical', 'plyometric'],
  },
  {
    id: 'drill-009',
    title: 'Midrange Pull-Up Jumper',
    subtitle: 'KD-style off-the-dribble',
    youtubeId: 'JFQRIqCGMCQ',
    category: 'shooting',
    difficulty: 'intermediate',
    durationMinutes: 20,
    sets: 4,
    reps: '10 makes',
    equipment: ['basketball', 'hoop'],
    coachNote: 'One dribble pull-up — create your own shot off the bounce.',
    tags: ['shooting', 'midrange', 'pull-up'],
  },
  {
    id: 'drill-010',
    title: 'Two-Ball Dribbling',
    subtitle: 'Coordination & handle strength',
    youtubeId: 'Tm8TZJBpbSA',
    category: 'ball-handling',
    difficulty: 'advanced',
    durationMinutes: 15,
    sets: 3,
    reps: '60 seconds each pattern',
    equipment: ['2 basketballs'],
    coachNote: 'Keep both balls bouncing at the same height. Eyes up.',
    tags: ['ball-handling', 'two-ball', 'coordination'],
  },
  {
    id: 'drill-011',
    title: 'Shell Drill Defensive Rotation',
    subtitle: 'Team defense principles',
    youtubeId: 'BZ0ySEWcN9Y',
    category: 'defense',
    difficulty: 'intermediate',
    durationMinutes: 20,
    sets: 3,
    reps: '5 minutes per set',
    equipment: ['basketball', 'cones', '4 players'],
    coachNote: 'Communicate every rotation. Call out screens and cutters.',
    tags: ['defense', 'rotation', 'shell-drill'],
  },
  {
    id: 'drill-012',
    title: 'Floater in the Paint',
    subtitle: 'High-arching touch finish',
    youtubeId: 'VHOyGMbGcl0',
    category: 'finishing',
    difficulty: 'intermediate',
    durationMinutes: 15,
    sets: 3,
    reps: '10 makes each side',
    equipment: ['basketball', 'hoop'],
    coachNote: 'Release off your front foot, arc the ball above the backboard level.',
    tags: ['finishing', 'floater', 'paint'],
  },
  {
    id: 'drill-013',
    title: 'Off-Ball Footwork Cuts',
    subtitle: 'V-cut and backdoor mastery',
    youtubeId: '0VaLGgww3rU',
    category: 'ball-handling',
    difficulty: 'beginner',
    durationMinutes: 15,
    sets: 3,
    reps: '10 each cut',
    equipment: ['basketball', 'cones', 'passer'],
    coachNote: 'Sell the fake first — your defender has to believe the opposite cut.',
    tags: ['movement', 'cutting', 'off-ball'],
  },
  {
    id: 'drill-014',
    title: 'Corner Three Shooting Program',
    subtitle: '500 corner threes workout',
    youtubeId: 'iL2JqEQ5v7E',
    category: 'shooting',
    difficulty: 'advanced',
    durationMinutes: 45,
    sets: 10,
    reps: '10 makes per spot',
    equipment: ['basketball', 'hoop', 'rebounder'],
    coachNote: 'Track your makes percentage. Goal is 40%+ from corner.',
    tags: ['shooting', 'corner-three', 'volume'],
  },
  {
    id: 'drill-015',
    title: '5-Dot Jump Shooting',
    subtitle: 'Catch and shoot from all spots',
    youtubeId: 'VPU6gY8JwJA',
    category: 'shooting',
    difficulty: 'beginner',
    durationMinutes: 20,
    sets: 2,
    reps: '5 makes per dot',
    equipment: ['basketball', 'hoop'],
    coachNote: 'Perfect your footwork on the catch before worrying about the shot.',
    tags: ['shooting', 'spots', 'beginner'],
  },
  {
    id: 'drill-016',
    title: 'Agility Ladder Footwork',
    subtitle: 'Quick feet for on-ball defense',
    youtubeId: 'dFLGnb9MGPE',
    category: 'athleticism',
    difficulty: 'beginner',
    durationMinutes: 15,
    sets: 4,
    reps: '4 runs each pattern',
    equipment: ['agility ladder'],
    coachNote: 'Drive your arms to increase leg speed. Stay on the balls of your feet.',
    tags: ['athleticism', 'agility', 'footwork'],
  },
  {
    id: 'drill-017',
    title: 'Drop Step Post Move',
    subtitle: 'Low-post scoring fundamentals',
    youtubeId: 'q8wvGnpWwf8',
    category: 'finishing',
    difficulty: 'intermediate',
    durationMinutes: 20,
    sets: 3,
    reps: '10 makes each side',
    equipment: ['basketball', 'hoop', 'pad holder'],
    coachNote: 'Feel the defender on your back before you drop. Protect the ball.',
    tags: ['finishing', 'post', 'drop-step'],
  },
  {
    id: 'drill-018',
    title: 'Help Defense Positioning',
    subtitle: 'Reading the floor, rotating right',
    youtubeId: 'LqpMdBEt5Gw',
    category: 'defense',
    difficulty: 'intermediate',
    durationMinutes: 20,
    sets: 3,
    reps: '15 minutes total',
    equipment: ['cones', 'basketball', '3+ players'],
    coachNote: 'Be in help position before the offense gets there. Anticipate, don\'t react.',
    tags: ['defense', 'help', 'positioning'],
  },
  {
    id: 'drill-019',
    title: 'Spin Move Finishing',
    subtitle: 'Reverse pivot to layup',
    youtubeId: 'C_T6iIxBIYk',
    category: 'finishing',
    difficulty: 'advanced',
    durationMinutes: 20,
    sets: 3,
    reps: '8 makes each side',
    equipment: ['basketball', 'hoop'],
    coachNote: 'Tight spin, protect the ball with both hands through the contact zone.',
    tags: ['finishing', 'spin', 'advanced'],
  },
  {
    id: 'drill-020',
    title: 'Triple Threat Jab Series',
    subtitle: 'Reading the defense from the wing',
    youtubeId: 'vHkVixfBpTE',
    category: 'ball-handling',
    difficulty: 'beginner',
    durationMinutes: 15,
    sets: 3,
    reps: '10 reps each option',
    equipment: ['basketball', 'cones'],
    coachNote: 'Make your jab threat realistic — the defender has to respect it.',
    tags: ['ball-handling', 'triple-threat', 'jab'],
  },
];
